//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WTBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code.
        /// </summary>
        public static string actSerialKeyLabel {
            get {
                return ResourceManager.GetString("actSerialKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string actVerifyBut {
            get {
                return ResourceManager.GetString("actVerifyBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide activation code.
        /// </summary>
        public static string actWinTitle {
            get {
                return ResourceManager.GetString("actWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTBot.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string butSolveCaptcha {
            get {
                return ResourceManager.GetString("butSolveCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string butTaskAdd {
            get {
                return ResourceManager.GetString("butTaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string butTaskEdit {
            get {
                return ResourceManager.GetString("butTaskEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string butTaskRemove {
            get {
                return ResourceManager.GetString("butTaskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card processing error occured.
        /// </summary>
        public static string cardError {
            get {
                return ResourceManager.GetString("cardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal bot error (Too fast / Sold out / Captcha error ).
        /// </summary>
        public static string checkoutError {
            get {
                return ResourceManager.GetString("checkoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string colId {
            get {
                return ResourceManager.GetString("colId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string colKeywords {
            get {
                return ResourceManager.GetString("colKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string colProgress {
            get {
                return ResourceManager.GetString("colProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string colRun {
            get {
                return ResourceManager.GetString("colRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string dataAddress1 {
            get {
                return ResourceManager.GetString("dataAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string dataAddress2 {
            get {
                return ResourceManager.GetString("dataAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card details.
        /// </summary>
        public static string dataCard {
            get {
                return ResourceManager.GetString("dataCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string dataCardExpire {
            get {
                return ResourceManager.GetString("dataCardExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string dataCardNumber {
            get {
                return ResourceManager.GetString("dataCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string dataCardType {
            get {
                return ResourceManager.GetString("dataCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string dataCity {
            get {
                return ResourceManager.GetString("dataCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string dataClear {
            get {
                return ResourceManager.GetString("dataClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string dataCountry {
            get {
                return ResourceManager.GetString("dataCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string dataCVV {
            get {
                return ResourceManager.GetString("dataCVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string dataEmail {
            get {
                return ResourceManager.GetString("dataEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string dataFullName {
            get {
                return ResourceManager.GetString("dataFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string dataPersonal {
            get {
                return ResourceManager.GetString("dataPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string dataPostcode {
            get {
                return ResourceManager.GetString("dataPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string dataRef {
            get {
                return ResourceManager.GetString("dataRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string dataSave {
            get {
                return ResourceManager.GetString("dataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string dataTel {
            get {
                return ResourceManager.GetString("dataTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add profile first. You can do that in settings..
        /// </summary>
        public static string errorAddProfileFirst {
            get {
                return ResourceManager.GetString("errorAddProfileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save a task without adding any items first..
        /// </summary>
        public static string errorCantSaveWithoutItems {
            get {
                return ResourceManager.GetString("errorCantSaveWithoutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A card error occured or item was sold out..
        /// </summary>
        public static string errorCardOrSoldOut {
            get {
                return ResourceManager.GetString("errorCardOrSoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string errorEnter {
            get {
                return ResourceManager.GetString("errorEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solved captchas are available to checkout..
        /// </summary>
        public static string errorNoCaptchasAvailable {
            get {
                return ResourceManager.GetString("errorNoCaptchasAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected size is not available. Aborting..
        /// </summary>
        public static string errorNoSizeAvailable {
            get {
                return ResourceManager.GetString("errorNoSizeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was not found on the website. Refreshing in.
        /// </summary>
        public static string errorNotFoundRefIn {
            get {
                return ResourceManager.GetString("errorNotFoundRefIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured:.
        /// </summary>
        public static string errorOccured {
            get {
                return ResourceManager.GetString("errorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product key isn&apos;t valid..
        /// </summary>
        public static string errorProductKeyNotValid {
            get {
                return ResourceManager.GetString("errorProductKeyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile doesn&apos;t exist or might have been deleted. Edit task and select another one..
        /// </summary>
        public static string errorProfileDoesntExist {
            get {
                return ResourceManager.GetString("errorProfileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item first..
        /// </summary>
        public static string errorSelectItemFirst {
            get {
                return ResourceManager.GetString("errorSelectItemFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select task first..
        /// </summary>
        public static string errorSelectTaskFirst {
            get {
                return ResourceManager.GetString("errorSelectTaskFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh interval.
        /// </summary>
        public static string labelRefreshFreq {
            get {
                return ResourceManager.GetString("labelRefreshFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string labelSettings {
            get {
                return ResourceManager.GetString("labelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding.
        /// </summary>
        public static string logAdding {
            get {
                return ResourceManager.GetString("logAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked out successfully.
        /// </summary>
        public static string logCheckedOutSuc {
            get {
                return ResourceManager.GetString("logCheckedOutSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found matching item:.
        /// </summary>
        public static string logFoundMatchingItem {
            get {
                return ResourceManager.GetString("logFoundMatchingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found total of.
        /// </summary>
        public static string logFoundTotalOf {
            get {
                return ResourceManager.GetString("logFoundTotalOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is no longer available in this size/style.
        /// </summary>
        public static string logItemNotAvailable {
            get {
                return ResourceManager.GetString("logItemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items in.
        /// </summary>
        public static string logItemsIn {
            get {
                return ResourceManager.GetString("logItemsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user data.
        /// </summary>
        public static string logLoadingData {
            get {
                return ResourceManager.GetString("logLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data loaded.
        /// </summary>
        public static string logLoadingDataFinished {
            get {
                return ResourceManager.GetString("logLoadingDataFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting new task named .
        /// </summary>
        public static string logStartedTaskWithId {
            get {
                return ResourceManager.GetString("logStartedTaskWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping task named .
        /// </summary>
        public static string logStoppingThreadWithIt {
            get {
                return ResourceManager.GetString("logStoppingThreadWithIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added.
        /// </summary>
        public static string logSuccessfullyAdded {
            get {
                return ResourceManager.GetString("logSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task removed..
        /// </summary>
        public static string logTaskRemoved {
            get {
                return ResourceManager.GetString("logTaskRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to cart.
        /// </summary>
        public static string logToCart {
            get {
                return ResourceManager.GetString("logToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to find matching item.
        /// </summary>
        public static string logTryingToFindItem {
            get {
                return ResourceManager.GetString("logTryingToFindItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:port.
        /// </summary>
        public static string lProxyAddress {
            get {
                return ResourceManager.GetString("lProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy name.
        /// </summary>
        public static string lProxyName {
            get {
                return ResourceManager.GetString("lProxyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lProxyPassword {
            get {
                return ResourceManager.GetString("lProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lProxyUsername {
            get {
                return ResourceManager.GetString("lProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string tabProfiles {
            get {
                return ResourceManager.GetString("tabProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string tabProxy {
            get {
                return ResourceManager.GetString("tabProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy/Settings.
        /// </summary>
        public static string tabProxyAndSettings {
            get {
                return ResourceManager.GetString("tabProxyAndSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string tabTasks {
            get {
                return ResourceManager.GetString("tabTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string taskInfoCategory {
            get {
                return ResourceManager.GetString("taskInfoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout delay.
        /// </summary>
        public static string taskInfoCheckoutDelay {
            get {
                return ResourceManager.GetString("taskInfoCheckoutDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string taskInfoColor {
            get {
                return ResourceManager.GetString("taskInfoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string taskInfoProfile {
            get {
                return ResourceManager.GetString("taskInfoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string taskInfoSize {
            get {
                return ResourceManager.GetString("taskInfoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task data.
        /// </summary>
        public static string taskInfoWindowName {
            get {
                return ResourceManager.GetString("taskInfoWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name.
        /// </summary>
        public static string taskName {
            get {
                return ResourceManager.GetString("taskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of miliseconds to wait before checkout. 2000 = 2seconds, 2500 = 2.5 seconds. We recommend you to check out atleast after 3 seconds, not to be recognized as bot..
        /// </summary>
        public static string toolTipCheckoutDelay {
            get {
                return ResourceManager.GetString("toolTipCheckoutDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorway of the item to be bought. Examples: &apos;yellow&apos; or &apos;magneta&apos;.
        /// </summary>
        public static string toolTipColor {
            get {
                return ResourceManager.GetString("toolTipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords separated with &apos;,&apos; signs, unambiguously identifying an item. Item name must contain every keyword given, to be bought. For example when you want to buy item named &quot;Vibrations Corduroy Trucker Jacket&quot; you can put &quot;vibrations,corduroy&quot;.
        /// </summary>
        public static string toolTipKeywords {
            get {
                return ResourceManager.GetString("toolTipKeywords", resourceCulture);
            }
        }
    }
}
